apiVersion: karpenter.k8s.aws/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  provider:
    subnetSelector:
      karpenter.sh/discovery: "self-managed-k8s"
    securityGroupSelector:
      karpenter.sh/discovery: "self-managed-k8s"
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.medium", "t3.large"]
  limits:
    resources:
      cpu: "100"
  ttlSecondsAfterEmpty: 30
