---
- name: Deploy Karpenter on Kubernetes Master
  hosts: master
  become: yes
  tasks:

    ### ✅ 1. Ensure KUBECONFIG is Set ###
    - name: Ensure KUBECONFIG is set for ec2-user
      lineinfile:
        path: /home/ec2-user/.bashrc
        line: "export KUBECONFIG=/home/ec2-user/.kube/config"
        create: yes

    - name: Source KUBECONFIG in current shell
      shell: source /home/ec2-user/.bashrc
      args:
        executable: /bin/bash

    ### ✅ 2. Create Karpenter Directory ###
    - name: Create Karpenter directory
      file:
        path: /home/ec2-user/self-managed-k8s-karpenter/karpenter
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    ### ✅ 3. Add & Update Helm Repositories ###
    - name: Add Karpenter Helm repo
      shell: helm repo list | grep -q "karpenter" || helm repo add karpenter https://charts.karpenter.sh
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config

    - name: Update Helm Repositories
      command: helm repo update
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config

    ### ✅ 4. Ensure Karpenter Namespace Exists ###
    - name: Create karpenter namespace
      shell: kubectl create namespace karpenter --dry-run=client -o yaml | kubectl apply -f -
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config

    ### ✅ 5. Install Karpenter Using Helm ###
    - name: Install Karpenter using Helm
      command: >
        helm upgrade --install karpenter karpenter/karpenter
        --namespace karpenter
        --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::{{ lookup('env', 'AWS_ACCOUNT_ID') }}:role/KarpenterRole"
        --set controller.clusterName="self-managed-k8s"
        --set defaultProvisioner.create=false
        --wait
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config

    ### ✅ 6. Ensure Karpenter CRDs Are Installed ###
    - name: Check if Karpenter CRDs are installed
      shell: kubectl get crds | grep 'karpenter'
      register: karpenter_crd_check
      ignore_errors: true
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config

    - name: Apply Karpenter CRDs (if missing)
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/aws/karpenter/main/pkg/apis/crds/karpenter.sh_provisioners.yaml
        kubectl apply -f https://raw.githubusercontent.com/aws/karpenter/main/pkg/apis/crds/karpenter.k8s.aws_awsnodetemplates.yaml
      when: karpenter_crd_check.rc != 0
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config

    ### ✅ 7. Wait for Karpenter Pods to be Ready ###
    - name: Wait for Karpenter pods to be ready
      shell: kubectl wait --namespace karpenter --for=condition=Ready pods --all --timeout=180s
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config
      ignore_errors: true

    ### ✅ 8. Create NodeTemplate ###
    - name: Write NodeTemplate YAML to Master Node
      copy:
        content: |
          apiVersion: karpenter.k8s.aws/v1alpha5
          kind: AWSNodeTemplate
          metadata:
            name: default
          spec:
            subnetSelector:
              karpenter.sh/discovery: "self-managed-k8s"
            securityGroupSelector:
              karpenter.sh/discovery: "self-managed-k8s"
            instanceProfile: "karpenter-instance-profile"
            amiFamily: AL2
        dest: /home/ec2-user/self-managed-k8s-karpenter/karpenter/nodetemplate.yaml
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Apply Karpenter NodeTemplate
      command: kubectl apply -f /home/ec2-user/self-managed-k8s-karpenter/karpenter/nodetemplate.yaml
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config

    ### ✅ 9. Create Provisioner ###
    - name: Write Provisioner YAML to Master Node
      copy:
        content: |
          apiVersion: karpenter.sh/v1alpha5
          kind: Provisioner
          metadata:
            name: default
          spec:
            providerRef:
              name: default
            requirements:
              - key: "karpenter.k8s.aws/instance-category"
                operator: In
                values: ["t3", "m5"]
            limits:
              resources:
                cpu: "100"
            consolidation:
              enabled: true
            ttlSecondsAfterEmpty: 30
            nodeSelector:
              kubernetes.io/role: worker
            tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
                effect: NoSchedule
        dest: /home/ec2-user/self-managed-k8s-karpenter/karpenter/provisioner.yaml
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Apply Karpenter Provisioner
      command: kubectl apply -f /home/ec2-user/self-managed-k8s-karpenter/karpenter/provisioner.yaml
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config
