---
- name: Deploy Karpenter on Kubernetes Master
  hosts: master
  become: yes
  tasks:

    - name: Ensure KUBECONFIG is set for ec2-user
      lineinfile:
        path: /home/ec2-user/.bashrc
        line: "export KUBECONFIG=/home/ec2-user/.kube/config"
        create: yes

    - name: Create Karpenter directory
      file:
        path: /home/ec2-user/self-managed-k8s-karpenter/karpenter
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Write NodeTemplate YAML to Master Node
      copy:
        content: |
          apiVersion: karpenter.k8s.aws/v1alpha5
          kind: AWSNodeTemplate
          metadata:
            name: default
          spec:
            subnetSelector:
              karpenter.sh/discovery: "self-managed-k8s"
            securityGroupSelector:
              karpenter.sh/discovery: "self-managed-k8s"
            instanceProfile: "karpenter-instance-profile"
            amiFamily: AL2
        dest: /home/ec2-user/self-managed-k8s-karpenter/karpenter/nodetemplate.yaml
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Write Provisioner YAML to Master Node
      copy:
        content: |
          apiVersion: karpenter.sh/v1alpha5
          kind: Provisioner
          metadata:
            name: default
          spec:
            providerRef:
              name: default
            requirements:
              - key: "karpenter.k8s.aws/instance-category"
                operator: In
                values: ["t3", "m5"]
            limits:
              resources:
                cpu: "100"
            consolidation:
              enabled: true
            ttlSecondsAfterEmpty: 30
        dest: /home/ec2-user/self-managed-k8s-karpenter/karpenter/provisioner.yaml
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Apply Karpenter NodeTemplate
      command: kubectl apply -f /home/ec2-user/self-managed-k8s-karpenter/karpenter/nodetemplate.yaml
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config

    - name: Apply Karpenter Provisioner
      command: kubectl apply -f /home/ec2-user/self-managed-k8s-karpenter/karpenter/provisioner.yaml
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config
