---
- name: Deploy Karpenter on Kubernetes Master
  hosts: master
  become: yes
  tasks:

    ### ✅ 1. Verify Karpenter IAM Role Permissions ###
    - name: Verify Karpenter IAM Role
      command: aws iam get-role-policy --role-name "KarpenterRole" --policy-name "KarpenterControllerPolicy"
      register: karpenter_iam_status
      ignore_errors: yes

    ### ✅ 2. Install Karpenter using Helm ###
    - name: Install Karpenter using Helm
      shell: >
        helm upgrade --install karpenter karpenter/karpenter
        --namespace karpenter
        --set serviceAccount.create=true
        --set serviceAccount.name=karpenter
        --set controller.clusterName="self-managed-k8s"
        --set controller.logLevel=debug
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config

    ### ✅ 3. Deploy Karpenter Provisioner ###
    - name: Apply Provisioner
      command: kubectl apply -f /home/ec2-user/self-managed-k8s-karpenter/karpenter/provisioner.yaml
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config
