---
- name: Install Kubernetes and Join Worker Nodes to Cluster
  hosts: workers
  become: yes
  tasks:

    ### ✅ 1. Wait for Kubernetes API Server to be Ready ###
    - name: Wait for Kubernetes API Server
      uri:
        url: "https://{{ groups['master'][0] }}:6443/healthz"
        method: GET
        validate_certs: no
      register: k8s_api_status
      until: k8s_api_status.status == 200
      retries: 30
      delay: 10

    ### ✅ 2. Join Worker Nodes to the Cluster ###
    - name: Fetch Join Command from Master
      slurp:
        src: /var/lib/kubeadm_join.sh
      register: kubeadm_join
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true

    - name: Write Join Command to Worker Nodes
      copy:
        content: "{{ kubeadm_join.content | b64decode }}"
        dest: /var/lib/kubeadm_join.sh
        mode: '0755'

    - name: Join Worker Node to Kubernetes Cluster
      command: bash /var/lib/kubeadm_join.sh
      args:
        creates: /etc/kubernetes/kubelet.conf

    ### ✅ 3. Restart Kubelet ###
    - name: Restart kubelet
      systemd:
        name: kubelet
        state: restarted
        enabled: yes
