# karpenter-provisioner.yaml - Defines Karpenter provisioner
apiVersion: karpenter.k8s.aws/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  provider:
    instanceProfile: "self-managed-k8s-instance-profile"
  ttlSecondsAfterEmpty: 30
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.medium", "t3.large", "t3.xlarge"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a", "us-east-1b"]
    - key: "karpenter.k8s.aws/capacity-type"
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: "100"
      memory: "200Gi"
